spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    beans:
      enabled: true
    caches:
      enabled: true